<?php

/**
 * Curated Google Font family names for the public menu (must match fonts.google.com).
 * Weights 400–700 are requested in the stylesheet URL.
 */
return [
    'families' => [
        'Almarai',
        'Amiri',
        'Aref Ruqaa',
        'Assistant',
        'Beiruti',
        'Cairo',
        'Changa',
        'DM Sans',
        'El Messiri',
        'Exo 2',
        'Fira Sans',
        'IBM Plex Sans',
        'IBM Plex Sans Arabic',
        'Inter',
        'Jost',
        'Katibeh',
        'Kufam',
        'Lalezar',
        'Lateef',
        'League Spartan',
        'Lexend',
        'Libre Franklin',
        'Literata',
        'Manrope',
        'Markazi Text',
        'Merriweather',
        'Mirza',
        'Mada',
        'Manjari',
        'Montserrat',
        'Mukta',
        'Noto Kufi Arabic',
        'Noto Naskh Arabic',
        'Noto Nastaliq Urdu',
        'Noto Sans',
        'Noto Sans Arabic',
        'Noto Sans Display',
        'Noto Sans HK',
        'Noto Sans JP',
        'Noto Sans KR',
        'Noto Sans SC',
        'Noto Sans TC',
        'Noto Serif',
        'Open Sans',
        'Oswald',
        'Outfit',
        'Playfair Display',
        'Plus Jakarta Sans',
        'Poppins',
        'PT Sans',
        'PT Serif',
        'Public Sans',
        'Quicksand',
        'Rakkas',
        'Raleway',
        'Readex Pro',
        'Reem Kufi',
        'Reem Kufi Fun',
        'Roboto',
        'Roboto Condensed',
        'Roboto Flex',
        'Rubik',
        'Scheherazade New',
        'Source Sans 3',
        'Source Serif 4',
        'Space Grotesk',
        'Space Mono',
        'Tajawal',
        'Tinos',
        'Ubuntu',
        'Varela Round',
        'Work Sans',
        'Zain',
    ],
];
